#:schema node_modules/wrangler/config-schema.json
name = "sublink-2026"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "4bb078f3d87e4553ade2c8dcf03c1bac" }
]

[assets]
directory = "./public"
